openapi: 3.0.3
info:
  title: Spec 4 — GET /api/me
  version: 1.0.0
paths:
  /api/me:
    get:
      summary: Get current authenticated user's basic profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                      role:
                        type: string
                        enum: [Basic, Admin]
        '401':
          description: Unauthorized (missing/invalid/expired token, or user not allowed)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        examples: [UNAUTHORIZED, TOKEN_EXPIRED]
                      message:
                        type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
