openapi: 3.0.3
info:
  title: Pre-Sales CRM Auth API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: User login and token issue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          email:
                            type: string
                          roleId:
                            type: string
                            nullable: true
                required: [data]
        '401':
          description: Invalid credentials
  /api/auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required: [refreshToken]
      responses:
        '200':
          description: New tokens issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                required: [data]
        '401':
          description: Invalid or expired refresh token
  /api/auth/logout:
    post:
      summary: Revoke session
      responses:
        '204':
          description: Logged out
        '401':
          description: Not authenticated
